# Generated by Django 5.0.7 on 2025-04-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fee_course_price_course_prerequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
