# Generated by Django 5.0.7 on 2025-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='myapp.course'),
        ),
    ]
