# Generated by Django 5.0.7 on 2025-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('software_dev', 'Software Development'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('networking', 'Networking & Infrastructure'), ('cloud_computing', 'Cloud Computing'), ('it_support', 'IT Support & Administration'), ('other', 'Other')], max_length=15)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('application_deadline', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
    ]
