# Generated by Django 5.0.7 on 2025-04-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0002_alter_course_duration_alter_course_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
